# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
#https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/build-artifacts?view=azure-devops&tabs=yaml
#https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml-task
#Your build pipeline references an undefined variable named ‘Parameters.RestoreBuildProjects’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

trigger:
- main1

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
steps:
- task: CmdLine@2
  inputs:
          script: |
            pushd simple-feed-reader
            dotnet restore
  displayName: "Restore packages"

- task: CmdLine@2
  inputs:
          script: |
            pushd simple-feed-reader
            dotnet build
  displayName: "Build packages"


#- task: UseDotNet@2
#  displayName: 'Use .NET Core sdk'
#  inputs:
 #   packageType: sdk
  #  version: 5.0.x
   # installationPath: $(Agent.ToolsDirectory)/dotnet
#- task: DotNetCoreCLI@2
#  displayName: Restore
#  inputs:
 #   command: restore
 #   projects: '$(Parameters.RestoreBuildProjects)'


#Yours build pipeline references an undefined variable named ‘Parameters.RestoreBuildProjects’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘BuildConfiguration’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972


#- task: DotNetCoreCLI@2
#  displayName: Build
 # inputs:
 #   projects: '$(Parameters.RestoreBuildProjects)'
  #  arguments: '--configuration $(BuildConfiguration)'



#Your build pipeline references an undefined variable named ‘Parameters.TestProjects’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references an undefined variable named ‘BuildConfiguration’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972


#- task: DotNetCoreCLI@2
 # displayName: Test
  #inputs:
   # command: test
    #projects: '$(Parameters.TestProjects)'
    #arguments: '--configuration $(BuildConfiguration)'


#1Your build pipeline references an undefined variable named ‘BuildConfiguration’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972


#- task: DotNetCoreCLI@2
 # displayName: Publish
  #inputs:
   # command: publish
    #publishWebProjects: True
    #arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    #zipAfterPublish: True

- #task: PublishBuildArtifacts@1
  #displayName: 'Publish Artifact'
  #inputs:
   # PathtoPublish: '$(build.artifactstagingdirectory)'
  #condition: succeededOrFailed()


